### ISSUE TITLE
[FEATURE] Compute nightly builds in staging branch

### ISSUE THREAD

**Issue by miguelgfierro** [recommenders-team/recommenders#1821]
### Description

It seems there is a way to compute the nightly builds in staging branch, see https://stackoverflow.com/questions/58798886/github-actions-schedule-operation-on-branch.

Basically, you can specify with parameters on the checkout action. This workflow will checkout the last commit on the some-branch branch.

```
name: Release Management
on: 
  schedule:
   - cron: "*/5 * * * *"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: some-branch
```

### Expected behavior with the suggested feature

We will create another action to perform the nightly build on staging branch, this will generate a new badge, so we will be able to track the two branches independently

### Other Comments
Original behavior https://github.com/microsoft/recommenders/blob/main/.github/workflows/azureml-cpu-nightly.yml#L18
